### ISSUE TITLE
Link to OSF for project

### ISSUE THREAD

**Issue by stephwright** [LibrariesPlus/LibsPlus#4]
@librlaurie was planning to do this

**Comment by librlaurie** [comment]
Looks like I don't have the rights to connect it, @stephwright . I can connect a bunch of my other repos, but not this one. Any chance you can connect it in OSF or give me admin access here?

**Comment by stephwright** [comment]
Hrm... I thought I made you an admin.  Lemme see what I can find out... yep. you're admin.  I'll try linking it.  where is the OSF project?

**Comment by stephwright** [comment]
Okay... did some more digging.  I had you as Admin for this repo but not owner of the organization.  I've now fixed that.  Maybe that will let you do it?

**Comment by librlaurie** [comment]
Hmm. Still can't add it. I can see a million repos from various orgs I'm part of, but still not this one.

**Comment by stephwright** [comment]
Well that's annoying... lemme look into it.  I would've thought you being an admin on this repo and an admin on the organization would give you access.  I'll dig through the settings and see if there's anything that could be blocking us there and do some web searching too.  If there's nothing obvious there, I'll reach out to OSF folks and see if they have some insight.

**Comment by stephwright** [comment]
Okay... looks like there were some restrictions on the org for 3d party connections.  I've removed all restrictions.  Want to give it another try?

**Comment by librlaurie** [comment]
Got it! thanks!
